### ISSUE TITLE
Error when importing XP network packages on React 

### ISSUE THREAD

**Issue by imabhijith25** [xp-network/xpjs#14]
I tried to install the XP network using the commands present in the documentation for my **react** project
`npm i --save xp.network @elrondnetwork/erdjs ethers @taquito/taquito @temple-wallet/dapp`

Now when I import packages like `import {
    ChainFactoryConfigs,
    ChainFactory,
    Chain,
    AppConfigs,
    ChainParams
} from "xp.network";`

 I am getting an error message like this
`ERROR in ./node_modules/@hashgraph/hethers/lib.esm/utils.js 30:0-36:107
export 'ErrorFragment' (reexported as 'ErrorFragment') was not found in '@ethersproject/abi' (possible exports: AbiCoder, ConstructorFragment, EventFragment, FormatTypes, Fragment, FunctionFragment, Indexed, Interface, LogDescription, ParamType, TransactionDescription, checkResultErrors, defaultAbiCoder)`

also
`ERROR in ./node_modules/@elrondnetwork/bls-wasm/bls_c.js 44:30-43
Module not found: Error: Can't resolve 'fs' in`

I am using react script 5.0.1 with config overrides as well. Also I tried with react script 4.0.2 without config-overrides but it gave all sorts of error related to solana

**Comment by AlexeyAdoniev** [comment]
Please make sure you have following configuration for your React App

1. Create 'config-overrides.js' in root folder:

```js

const webpack = require("webpack");

module.exports = function override(webpackConfig) {
  webpackConfig.resolve.fallback = {
    url: false,
    querystring: false,
    assert: require.resolve("assert"),
    crypto: require.resolve("crypto-browserify"),
    path: require.resolve("path"),
    fs: false,
    os: false,
    http: require.resolve("stream-http"),
    https: require.resolve("https-browserify"),
    buffer: require.resolve("buffer"),
    stream: require.resolve("stream-browserify"),
  };

  webpackConfig.ignoreWarnings = [/Failed to parse source map/];


  webpackConfig.plugins.push(
    new webpack.ProvidePlugin({
      process: "process/browser",
      Buffer: ["buffer", "Buffer"],
    })
  );

  return webpackConfig;
};

```
2. In package.json make sure you have following deps and scripts: 

```json
{
    "dependencies": {
    "https-browserify": "^1.0.0",
    "path": "^0.12.7",
    "react-app-rewire-babel-loader": "^0.1.1",
    "react-app-rewired": "^2.2.1",
    "react-scripts": "5.0.1",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0"
  },

  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build --max_old_space_size=8192",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject"
  }
}

```
3. Install packages and run start command.

I tested on https://github.com/imabhijith25/samplereactapp (with yarn) and it compiled without bugs

**Comment by imabhijith25** [comment]
Thanks it worked!
